feat: Getting started screen with user account validation via email
fossasia/open-event-orga-iOS pull request #26
Opened 2019-04-07 08:05 UTC by dilum1995

Implemented: #20 

Changes: 
Implemented the getting started screen which asks the user for the email to validate whether the
user already has an account or not.
if the user has an account already the starting screen will navigate directly to the login screen
after the email validation. if the user doesn't have an account it will redirect the user to the signup screen.

Screenshots for the change: 
<img width="421" alt="Screen Shot 2019-04-07 at 1 33 27 PM" src="https://user-images.githubusercontent.com/23298579/55680633-c6831c80-5939-11e9-9079-03f4698c8b49.png">

2019-04-10 18:35 UTC, chashmeetsingh requested changes
Move all the constants to a constants file, refer SUSI_iOS repo. Looks good otherwise.

2019-04-10 18:35 UTC, chashmeetsingh commented on EventyayOrganizer/Controllers/SignUpController/SignUpVCMethods.swift
> +        addressTextField.text = "https://api.eventyay.com/v1/"
Add all constants in a constants file.

2019-04-10 18:35 UTC, chashmeetsingh commented on EventyayOrganizer/Network/APIClient.swift
> +   var kBaseURL = "https://open-event-api-dev.herokuapp.com/v1"
Same here.

2019-04-12 05:21 UTC, dilum1995 commented
@chashmeetsingh sure I will add a constants file and move all the URLs and relevant data there.

2019-04-12 10:26 UTC, dilum1995 commented
@chashmeetsingh could you please have a look into this #29 PR since it includes some relevant changes to this PR.

2019-04-25 08:26 UTC, chashmeetsingh commented
Please fix the lint issues.

2019-04-26 19:03 UTC, dilum1995 commented
Oh sure I will fix them.

2019-05-10 14:16 UTC, chashmeetsingh approved these changes
LGTM

2019-05-11 09:39 UTC, jogendra approved these changes

2019-05-11 09:41 UTC, merged