Implemented new progress HUD
fossasia/open-event-orga-iOS pull request #31
Opened 2019-06-12 05:35 UTC by obitodarky

- Fixes #30 
- Also fixed an issue where users were able to interact with the app while in the loading state

**Changes:** 

1. Added SVProgressHUD in Podfile
2. Removed old IndicatorView and used SVProgressHUD in the Welcome Screen.
3. Added a method to ignore Interaction Events while loading.

**Screenshots for the change:** 

![Screenshot 2019-06-11 at 12 51 20 PM](https://user-images.githubusercontent.com/21317964/59325523-0af7b380-8d01-11e9-88f5-758bda8a1468.png)

2019-06-12 05:46 UTC, kushthedude commented
@obitodarky Fix lint issues

2019-06-12 05:47 UTC, kushthedude requested changes
@obitodarky Fix lint issues

2019-06-14 03:45 UTC, baquer requested changes

2019-06-14 03:45 UTC, baquer commented on EventyayOrganizer/Controllers/WelcomeController/WelcomeVCMethods.swift
> +        SVProgressHUD.show(withStatus: "Logging In")
Put a string in a constant file.

2019-06-14 03:45 UTC, baquer commented on Podfile.lock
> +COCOAPODS: 1.5.3
Update your pods to the latest version.

2019-06-14 08:59 UTC, obitodarky commented
I'll fix the lint issues and perform these changes and file a different PR. I am closing this for now.

2019-06-14 08:59 UTC, closed without merging